### PR TITLE
private/sample_aliases: fix typo

### PR DESCRIPTION
**Pull request by alurm**

### CODE REVIEW

**Comment by uwla** [comment]
I merged your PR via the command line because I do not like GitHub's merge button since GitHub creates a "merge commit" with an awful commit message.

Your commit is already in the branch master, I just adapted it to follow a commit standard:

https://www.conventionalcommits.org

Recently, I've been following conventional commits standard to improve my commit messages (which were very bad before it) and code quality.

**Comment by uwla** [comment]
How do I mark it as merged? I'd like GitHub to mark it as merged

**Comment by alurm** [comment]
No idea

**Comment by alurm** [comment]
I'm not sure if it's possible, since it's technically not merged. Commit hash is different, since the message is different. I think it's fine to leave it as is

**Pull request closed without merging**
